
###

POST http://localhost:8080/api/categories
Content-Type: application/json

{
  "name": "Postbol2"
}

###
GET http://localhost:8080/api/categories
Accept: application/json

###
POST http://localhost:8080/api/questions
Content-Type: application/json


{
  "question": "first Question",
"answers": [
"elsovalasz",
        "masodik valasz"
],
  "correctAnswerIndex": 1,
  "categoryId": "619ec2f67f3222af371920ab"
}


###
GET http://localhost:8080/api/questions
Accept: application/json

###

GET http://localhost:8080/api/questions/61a7e5b382323d26dbc5dc1d
Accept: application/json

###